/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "@aws-amplify/ui-react/internal";
import { Flex, Text } from "@aws-amplify/ui-react";
export default function Estimate(props) {
  const { overrides, ...rest } = props;
  return (
    <Flex
      gap="5px"
      direction="column"
      width="594px"
      height="unset"
      justifyContent="flex-start"
      alignItems="center"
      overflow="hidden"
      position="relative"
      padding="0px 50px 0px 50px"
      backgroundColor="rgba(255,255,255,1)"
      {...getOverrideProps(overrides, "Estimate")}
      {...rest}
    >
      <Text
        fontFamily="Inter"
        fontSize="27.647998809814453px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="34.55999755859375px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        shrink="0"
        position="relative"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Total FT^2 = 2360 FT^2"
        {...getOverrideProps(overrides, "Total FT^2 = 2360 FT^2")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="27.647998809814453px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="34.55999755859375px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        shrink="0"
        position="relative"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Total YD^3 = 30 YD^3"
        {...getOverrideProps(overrides, "Total YD^3 = 30 YD^3")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="27.647998809814453px"
        fontWeight="700"
        color="rgba(13,26,38,1)"
        lineHeight="34.55999755859375px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="260px"
        height="41px"
        gap="unset"
        alignItems="unset"
        shrink="0"
        position="relative"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Concrete&#xA;"
        {...getOverrideProps(overrides, "label4079322")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="27.647998809814453px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="34.55999755859375px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        shrink="0"
        position="relative"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Cost per YD^3 = $125 YD^3"
        {...getOverrideProps(overrides, "Cost per YD^3 = $125 YD^3")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="27.647998809814453px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="34.55999755859375px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        shrink="0"
        position="relative"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Total Cost = $3750 + $1000 for pump"
        {...getOverrideProps(overrides, "Total Cost = $3750 + $1000 for pump")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="27.647998809814453px"
        fontWeight="700"
        color="rgba(13,26,38,1)"
        lineHeight="34.55999755859375px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="260px"
        height="41px"
        gap="unset"
        alignItems="unset"
        shrink="0"
        position="relative"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Vapor Barrier"
        {...getOverrideProps(overrides, "label4079321")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="27.647998809814453px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="34.55999755859375px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        shrink="0"
        position="relative"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Total Cost = $200"
        {...getOverrideProps(overrides, "Total Cost = $200")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="27.647998809814453px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="34.55999755859375px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        shrink="0"
        position="relative"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Cost = $100 per 2000ft^2 "
        {...getOverrideProps(overrides, "Cost = $100 per 2000ft^2")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="27.647998809814453px"
        fontWeight="700"
        color="rgba(13,26,38,1)"
        lineHeight="34.55999755859375px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="260px"
        height="41px"
        gap="unset"
        alignItems="unset"
        shrink="0"
        position="relative"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Welded Wire Mesh"
        {...getOverrideProps(overrides, "label4079320")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="27.647998809814453px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="34.55999755859375px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        shrink="0"
        position="relative"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Cost = $7 per 45ft^2 "
        {...getOverrideProps(overrides, "Cost = $7 per 45ft^2")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="27.647998809814453px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="34.55999755859375px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        shrink="0"
        position="relative"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Total Cost = $371"
        {...getOverrideProps(overrides, "Total Cost = $371")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="27.647998809814453px"
        fontWeight="700"
        color="rgba(13,26,38,1)"
        lineHeight="34.55999755859375px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="182px"
        height="36px"
        gap="unset"
        alignItems="unset"
        shrink="0"
        position="relative"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Tax (8.5%)"
        {...getOverrideProps(overrides, "label4079319")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="27.647998809814453px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="34.55999755859375px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        shrink="0"
        position="relative"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children=" = $452.28"
        {...getOverrideProps(overrides, "= $452.28")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="27.647998809814453px"
        fontWeight="700"
        color="rgba(13,26,38,1)"
        lineHeight="34.55999755859375px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="77px"
        height="37px"
        gap="unset"
        alignItems="unset"
        shrink="0"
        position="relative"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Total"
        {...getOverrideProps(overrides, "label40701203")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="27.647998809814453px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="34.55999755859375px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        shrink="0"
        position="relative"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children=" = $5773.28"
        {...getOverrideProps(overrides, "= $5773.28")}
      ></Text>
    </Flex>
  );
}
